CREATE TABLE users ( 
  id SERIAL PRIMARY KEY,
  email VARCHAR(50) UNIQUE NOT NULL,
  user_name VARCHAR(50) UNIQUE NOT NULL,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL
  )